version: '3'

services:
  app:
    image: node:latest
    command: 'yarn start'
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mysql
    ports:
      - 3333:3333

  mysql:
    image: mariadb:10.6
    ports:
      - 3334:3306
    expose:
      - 3334
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project

volumes:
  database_data:
    driver: local
